spring:
  application:
    name: cms
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
  dataSource:
    url: jdbc:h2:mem:cms;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      setting:
        trace: false
        web-allow-others: true
  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
job:
  postDel:
    folderPath: /Users/X1/Documents/java/cms/data
server:
  port: 8080